parameters:
  env(BOT_TOKEN): ''
  env(BOT_NAME): ''
  env(ADMIN_IDS): ''
  env(PROXY): ''

services:
  _defaults:
    autowire: true
    autoconfigure: true

  guzzle_telegram_client:
    class: GuzzleHttp\Client
    arguments:
      - base_uri: "https://api.telegram.org"
        proxy: '%env(PROXY)%'

  Porox\TelegramBotBundle\Service\TelegramService:
    public: true
    arguments:
      $api_key: '%env(BOT_TOKEN)%'
      $bot_username: '%env(BOT_NAME)%'
      $clientHttp: '@guzzle_telegram_client'

  telegram_bot:
    public: true
    alias: Porox\TelegramBotBundle\Service\TelegramService

  Longman\TelegramBot\Telegram:
    public: true
    alias: Porox\TelegramBotBundle\Service\TelegramService

  Porox\TelegramBotBundle\Service\Commands\GenericCommand:
    autowire: true
    tags: [telegram_bot_command]

  Porox\TelegramBotBundle\Service\Commands\HelpCommand:
    autowire: true
    tags: [telegram_bot_command]
